version: "2"
services:
  spark-master:
    image: apache/spark:3.3.1
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - /root/hadoop-cluster/hadoop-config:/opt/hadoop/conf
    command: /bin/bash -c "/opt/spark/bin/start-master.sh"

  spark-worker:
    image: apache/spark:3.3.1
    volumes:
      - /root/hadoop-cluster/hadoop-config:/opt/hadoop/conf
    command: /bin/bash -c "/opt/spark/bin/start-worker.sh spark://spark-master:7077"
    depends_on:
      - spark-master